name: Generate Contribution Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=C39583&color_dots[0]=441015&color_dots[1]=582419&color_dots[2]=786F50&color_dots[3]=967F59&color_dots[4]=C39583
            dist/github-contribution-grid-snake-dark.svg?color_snake=C39583&color_dots[0]=441015&color_dots[1]=582419&color_dots[2]=786F50&color_dots[3]=967F59&color_dots[4]=C39583

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

